- name: criando um loop 
  hosts: all 
  tasks:
   - name: instalando epel-release
     yum:
      name: epel-release
     when: ansible_os_family == "RedHat" 


   - name: instalando pacotes 
     package: 
      name: "{{ item }}" 
     with_items: 
       - vim 
       - cowsay
       - figlet 
    
